# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  # Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
  - gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
  - gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail && xcodebuild test -workspace Example/GridView.xcworkspace -scheme GridView-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
